front/config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'

  match 'auth',     to: 'authentication#index',   via: [:get,:post]
  get 'signup',     to: 'authentication#signup'
  match 'user',     to: 'users#index',            via: [:get,:post]
  match 'files',    to: 'files#index',            via: [:get,:post]

  get 'liveness',	to: 'liveness#liveness'
end

front/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Response
  include ExceptionHandler

  # called before every action on controllers
  before_action :authorize_request
  attr_reader :current_user

  private

  def authorize_request
    @current_user = (AuthorizeApiRequest.new(cookies).call())[:user]
  end
end

front/app/controllers/authentication_controller.rb
require 'net/http'
require 'json'

class AuthenticationController < ApplicationController
  skip_before_action :authorize_request
  def index
    if request.post?
      if params.has_key?(:signup)
        path = '/user'
      else
        path = '/auth'
      end
      Net::HTTP.start(Rails.application.secrets.auth_api_addr, Rails.application.secrets.auth_api_port) { |http|
        res = http.send_request(request.method, path, auth_params.as_json.to_query)
        case res
          when Net::HTTPSuccess
            auth_token ||= JSON.parse(res.body)["token"]
            cookies[:session] = auth_token
          when Net::HTTPUnauthorized
            flash.now[:error] = "Wrong Username or Password"
          when Net::HTTPConflict
            flash.now[:error] = "User Already Exists"
          else
            flash.now[:error] = JSON.parse(res.body)["message"]
        end
      }
    end
    begin
      if authorize_request.present?
        redirect_to user_path
      end
    rescue
      nil
    end
  end

  def signup
    begin
      if authorize_request.present?
        redirect_to user_path
      end
    rescue
      nil
    end
  end

  private

  def auth_params
    params.permit(:username, :password)
  end
end

front/app/controllers/concerns/exception_handler.rb
module ExceptionHandler
  extend ActiveSupport::Concern

  # Define custom error subclasses - rescue catches `StandardErrors`
  class AuthenticationError < StandardError; end
  class MissingToken < StandardError; end
  class InvalidToken < StandardError; end

  included do
    # Define custom handlers
    rescue_from ActiveRecord::RecordInvalid, with: :four_twenty_two
    rescue_from ExceptionHandler::AuthenticationError, with: :unauthorized_request
    rescue_from ExceptionHandler::MissingToken, with: :four_twenty_two
    rescue_from ExceptionHandler::InvalidToken, with: :four_twenty_two
  end

  private

  def four_twenty_two(e)
    flash.now[:error] = e.message
    redirect_to auth_path
  end

  def unauthorized_request(e)
    flash.now[:error] = e.message
    redirect_to auth_path
  end
end

front/app/controllers/files_controller.rb
class FilesController < ApplicationController
  def index
    if @current_user['is_admin'] != true
      flash.now[:error] = "File Upload is Temporary Disable for Users"
      return
    end
    suffix = ''
    if request.get?
      if params.has_key?(:filename)
        path = '/download'
        suffix = Base64.encode64(params['filename']).strip
      else
        path = '/list'
      end
    else
      path = '/upload'
    end
    if request.headers['Content-Type'].present?
      ct = request.headers['Content-Type']
    else
      ct = 'application/x-www-form-urlencoded'
    end
    Net::HTTP.start(Rails.application.secrets.files_api_addr, Rails.application.secrets.files_api_port) { |http|
      res = http.send_request(request.method, '/api' + path + '/' + @current_user['user_id'].to_s + '/' + suffix, request.raw_post, {'Content-Type'=>ct})
      case res
        when Net::HTTPSuccess
          if request.get?
            if params.has_key?(:filename)
              send_data res.body, filename: params['filename']
            else
              @files = JSON.parse(res.body)["files"]
            end
          else
            flash[:notice] = 'File Uploaded'
            redirect_to files_path
          end
        when Net::HTTPNotFound
          flash.now[:error] = "File not found"
        else
          flash.now[:error] = JSON.parse(res.body)["message"]
      end
    }
  end
end

front/app/controllers/liveness_controller.rb
class LivenessController < ActionController::API
  def liveness
    render :text => 'ok'
  end
end

front/app/controllers/main_controller.rb
class MainController < ApplicationController
  skip_before_action :authorize_request

end

front/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    req_params = params
    if request.post?
      req_params = user_update_params  
    end
    req_params['id'] = @current_user['user_id']
    Net::HTTP.start(Rails.application.secrets.auth_api_addr, Rails.application.secrets.auth_api_port) { |http|
      res = http.send_request(request.method, '/user', req_params.as_json.to_query)
      case res
      when Net::HTTPSuccess
        if request.get?
          @user_data ||= JSON.parse(res.body)
        else
          auth_token ||= JSON.parse(res.body)["token"]
          cookies[:session] = auth_token
        end
      else
        flash.now[:error] = JSON.parse(res.body)["message"]
      end
    }
  end

  private

  def user_update_params
    params.permit(:username, :password)
  end
end

front/app/views/authentication/index.html.erb
<div class="login-dark">
  <form method="post">
    <h2 class="sr-only">Login Form</h2>
    <div class="illustration"><i class="icon ion-ios-locked-outline"></i></div>
    <div class="form-group"><input class="form-control" type="text" name="username" placeholder="Username"></div>
    <div class="form-group"><input class="form-control" type="password" name="password" placeholder="Password"></div>
    <div class="form-group"><button class="btn btn-primary btn-block" type="submit" name="login">Log In</button></div>
  </form>
</div>

front/app/views/authentication/signup.html.erb
<div class="login-dark">
  <form method="post" action="<%= auth_path %>">
    <h2 class="sr-only">Signup Form</h2>
    <div class="illustration"><i class="icon ion-ios-unlocked-outline"></i></div>
    <div class="form-group"><input class="form-control" type="text" name="username" placeholder="Username"></div>
    <div class="form-group"><input class="form-control" type="password" name="password" placeholder="Password"></div>
    <div class="form-group"><button class="btn btn-primary btn-block" type="submit" name="signup">Signup</button></div>
  </form>
</div>

front/app/views/files/index.html.erb
<div class="jumbotron">

  <div class="input-group mb-3">
    <div class="custom-file">
      <input type="file" class="custom-file-input" id="inputGroupFile02">
      <label class="custom-file-label" for="inputGroupFile02">Choose file</label>
    </div>
    <div class="input-group-append">
      <button class="btn btn-outline-secondary" id="submit_file" type="button">Upload</button>
    </div>
  </div>

  <script>
      $('#inputGroupFile02').on('change',function(){
          //get the file name
          var filename = $(this).val();
          filename = filename.substring(filename.lastIndexOf("\\") + 1, filename.length);
          //replace the "Choose a file" label
          $(this).next('.custom-file-label').html(filename);
      });

      $('#submit_file').click(function() {
          var fd = new FormData();
          var files = $('#inputGroupFile02')[0].files[0];
          fd.append('file', files);
          $.ajax({
              url: 'files',
              type: 'post',
              data: fd,
              contentType: false,
              processData: false,
              success: function (response) {
              },
          });
      });

  </script>

  <hr>
  <% if @files.present? %>
    <table class="table table-striped table-dark">
      <tr>
        <th>Filename (Download)</th>
      </tr>
    <% @files.each do |file| %>
      <tr>
        <td><%= link_to file, controller: "files", action: "index", filename: file %></td>
      </tr>
    <% end %>
    </table>
  <% end %>
</div>

front/app/views/layouts/_footer.html.erb
<!-- POWERED BY 

front/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

front/app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "FileSh4r3r", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>

    <button class="btn btn-sm btn-outline-secondary my-2 my-sm-0" id="logout_button" type="button">Log Out</button>

  </nav>
</div>

<script>
  $('#logout_button').click(function () {

      var cookies = document.cookie.split(";");

      for (var i = 0; i < cookies.length; i++) {
          var cookie = cookies[i];
          var eqPos = cookie.indexOf("=");
          var name = eqPos > -1 ? cookie.substr(0, eqPos) : cookie;
          document.cookie = name + "=;expires=Thu, 01 Jan 1970 00:00:00 GMT";
          window.location.href = '/';
      }
  })
</script>

front/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class='nav-item'><%= link_to 'Profile', user_path, class: 'nav-link' %></li>
<li class='nav-item'><%= link_to 'Files', files_path, class: 'nav-link' %></li>
<li class='nav-item'><%= link_to 'Login', auth_path, class: 'nav-link' %></li>
<li class='nav-item'><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>

front/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FileSh4r3r" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "FileSh4r3r" %>">
    <script src="/static/jquery-3.3.1.slim.min.js"></script>
    <script src="/static/popper.min.js"></script>
    <script src="/static/bootstrap.min.js"></script>
    <link rel="stylesheet" href="static/custom.css">
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
      <%= render 'layouts/footer' %>
    </main>
  </body>
</html>

front/app/views/main/index.html.erb
<div class="jumbotron">
  <h1 class="display-2">FileSh4r3r</h1>
  <p class="lead">
    We got the super file sharer!
  </p>
</div>

front/app/views/users/index.html.erb
<div class="jumbotron">
  <h1>Profile</h1>
  <% if defined?(@user_data) %>
    <p class="username"><strong>Username: </strong> <%= @user_data['username']%> </p>
  <% end %>
  <% if defined?(@current_user) %>
    <p class="user-id"><strong>UserID: </strong> <%= @current_user['user_id'] %></p>
    <%if @current_user['is_admin'] == true %>
      <p class="role"><strong>Role: </strong> Admin </p>
    <% else %>
      <p class="role"><strong>Role: </strong> User </p>
    <% end %>
  <% end %>
</div>

<div class="jumbotron">
  <h1>Credentials</h1>
  <form class="form-inline" method="post" action="user">
    <% if defined?(@user_data) %>
      <input type="hidden" name="username" value="<%= @user_data['username'] %>">
    <% end %>
    <div class="form-group mr-sm-3 mb-2">
      <label for="inputPassword" class="sr-only">New Password</label>
      <input type="password" name="password" class="form-control" id="inputPassword" placeholder="new password">
    </div>
    <button type="submit" class="btn btn-primary mb-2">Change password</button>
  </form>

</div>